name: Run 01 Intestazione - EasyPrev.py

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get install -y python3-tk
        pip install -r requirements.txt

    - name: Run 01 Intestazione - EasyPrev.py
      run: |
        xvfb-run python "01 Intestazione - EasyPrev.py"
